-- Knowledge Module: Private Document Storage
-- Run once per Supabase instance.
-- This creates a private storage bucket for document files and restricts
-- access so only admins can upload/delete; signed URLs are generated
-- server-side via the get-document-url Edge Function.

-- -----------------------------------------------------------------------
-- 1. Create the private documents bucket
-- -----------------------------------------------------------------------
-- IMPORTANT: Create the bucket via the Supabase Dashboard (Storage → New Bucket)
--   Name:    documents
--   Public:  false  (private)
--
-- Direct SQL inserts into storage.buckets do not initialise the internal
-- storage metadata properly and will result in 400 errors on upload.
-- The RLS policies below are all you need to run in the SQL editor.
--
-- If you prefer SQL-only (e.g. for scripted onboarding), use the
-- Supabase Management API:
--   POST /v1/projects/{ref}/storage/buckets  { "name": "documents", "public": false }

-- -----------------------------------------------------------------------
-- 2. RLS: only client_admin / super_admin may upload or delete files
--    (Signed URLs for reading are generated by the Edge Function using
--     the service role key, so users do not need direct storage SELECT.)
-- -----------------------------------------------------------------------
DROP POLICY IF EXISTS "Admins can manage document files" ON storage.objects;

CREATE POLICY "Admins can manage document files"
ON storage.objects
FOR ALL
TO authenticated
USING (
  bucket_id = 'documents'
  AND EXISTS (
    SELECT 1 FROM public.user_roles
    WHERE user_id = auth.uid()
      AND role IN ('super_admin', 'client_admin')
  )
)
WITH CHECK (
  bucket_id = 'documents'
  AND EXISTS (
    SELECT 1 FROM public.user_roles
    WHERE user_id = auth.uid()
      AND role IN ('super_admin', 'client_admin')
  )
);
