-- Knowledge Module: Private Document Storage
-- Run once per Supabase instance.
-- This creates a private storage bucket for document files and restricts
-- access so only admins can upload/delete; signed URLs are generated
-- server-side via the get-document-url Edge Function.

-- -----------------------------------------------------------------------
-- 1. Create the private documents bucket
-- -----------------------------------------------------------------------
-- IMPORTANT: Create the bucket via the Supabase Dashboard (Storage → New Bucket)
--   Name:    documents
--   Public:  false  (private)
--
-- Direct SQL inserts into storage.buckets do not initialise the internal
-- storage metadata properly and will result in 400 errors on upload.
-- The RLS policies below are all you need to run in the SQL editor.
--
-- If you prefer SQL-only (e.g. for scripted onboarding), use the
-- Supabase Management API:
--   POST /v1/projects/{ref}/storage/buckets  { "name": "documents", "public": false }

-- -----------------------------------------------------------------------
-- 2. Helper function for the storage RLS check
--
--    WHY a SECURITY DEFINER function?
--    When storage.objects RLS directly queries public.profiles, those
--    queries trigger profiles' own RLS, which in turn queries profiles
--    again (the manager chain). This recursive evaluation causes a TCP
--    timeout instead of a clean 403. A SECURITY DEFINER function runs
--    as postgres (bypasses RLS on the tables it queries internally),
--    breaking the recursion. CREATE OR REPLACE is idempotent.
-- -----------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.can_manage_documents()
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT
    -- admins
    EXISTS (
      SELECT 1 FROM user_roles
      WHERE user_id = auth.uid()
        AND role IN ('super_admin', 'client_admin')
    )
    OR
    -- managers (department managers)
    EXISTS (
      SELECT 1 FROM departments
      WHERE manager_id = auth.uid()
    )
    OR
    -- managers (have direct reports)
    EXISTS (
      SELECT 1 FROM profiles
      WHERE manager = auth.uid()
    );
$$;

-- -----------------------------------------------------------------------
-- 3. RLS: admins and managers may upload/delete files
--    (Signed URLs for reading are generated by the Edge Function using
--     the service role key, so users do not need direct storage SELECT.)
-- -----------------------------------------------------------------------
DROP POLICY IF EXISTS "Admins can manage document files"                   ON storage.objects;
DROP POLICY IF EXISTS "Managers can manage document files"                 ON storage.objects;
DROP POLICY IF EXISTS "Admins and managers can manage document files"      ON storage.objects;

CREATE POLICY "Admins and managers can manage document files"
ON storage.objects
FOR ALL
TO authenticated
USING  (bucket_id = 'documents' AND public.can_manage_documents())
WITH CHECK (bucket_id = 'documents' AND public.can_manage_documents());
